name: "Alt Suggestor"
description: "Looks for missing inline image alt text and suggests them"

inputs:
  owner: 
    description: "Repository Owner"
    required: true
  repo:
    description: "Repository Name"
    required: true
  branch:
    description: "Branch Name"
    required: true
  token:
    description: "GitHub Token"
    required: true
  pull_number:
    description: "Pull Request Number"
    required: true
  commit_id:
    description: "Commit ID"
    required: true
  ENDPOINT_URL:
    description: "Azure Endpoint Url"
    required: true
  AZURE_KEY:
    description: "Azure key"
    required: true  

runs: 
  using: node16
  main: index.js