name: "Alt Suggestor"
description: "Looks for missing inline image alt text and suggests them"
inputs:
  ENDPOINT_URL:
    description: "Endpoint url"
    required: true
runs: 
  using: node16
  main: index.js